# Generated by Django 3.1 on 2021-02-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_auto_20210214_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
    ]
