# Generated by Django 3.1 on 2021-02-15 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import info_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_app', '0004_auto_20210215_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='taught_by',
            field=models.ForeignKey(limit_choices_to=info_app.models.thifunc, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
