# Generated by Django 3.1 on 2021-02-16 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_app', '0005_auto_20210215_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections_offered',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
