# Generated by Django 3.1 on 2021-02-16 17:09

from django.conf import settings
from django.db import migrations, models
import info_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_app', '0007_auto_20210216_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections_offered',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to=info_app.models.thifunc2, to=settings.AUTH_USER_MODEL),
        ),
    ]
