# Generated by Django 3.1 on 2021-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0008_auto_20210216_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='for_session',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2017', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='for_semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10),
        ),
        migrations.DeleteModel(
            name='semester',
        ),
    ]
