# Generated by Django 3.1 on 2021-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0009_auto_20210221_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='for_semester_year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], default='2021', max_length=10),
            preserve_default=False,
        ),
    ]
