# Generated by Django 3.1 on 2021-02-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_app', '0009_auto_20210221_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], default='Fall', max_length=10)),
                ('for_session', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2017', max_length=10)),
                ('for_section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=10)),
                ('monday', models.CharField(blank=True, max_length=400, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=400, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=400, null=True)),
                ('thursday', models.CharField(blank=True, max_length=400, null=True)),
                ('friday', models.CharField(blank=True, max_length=400, null=True)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_app.department')),
            ],
        ),
    ]
