# Generated by Django 3.1 on 2021-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='for_semester_year',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], default='2021', max_length=10),
        ),
    ]
