# Generated by Django 3.1 on 2021-02-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_gen_app', '0002_timetable_for_semester_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetable',
        ),
    ]
