# Generated by Django 3.1 on 2021-02-14 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='time_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (1, 1), (2, 2), (3, 3)])),
                ('end_time', models.IntegerField(choices=[(9, 9), (10, 10), (11, 11), (12, 12), (1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('cnic', models.CharField(max_length=20)),
                ('profile_type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20)),
                ('preferred_slot_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_1', to='profile_app.time_slots')),
                ('preferred_slot_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_2', to='profile_app.time_slots')),
                ('preferred_slot_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_3', to='profile_app.time_slots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
