# Generated by Django 3.1 on 2021-02-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20210214_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_slot_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_1', to='profile_app.time_slots'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_slot_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_2', to='profile_app.time_slots'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_slot_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_3', to='profile_app.time_slots'),
        ),
    ]
