# Generated by Django 3.1 on 2021-02-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0008_auto_20210216_2209'),
        ('profile_app', '0003_auto_20210214_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_app.department'),
        ),
    ]
