# Generated by Django 3.1 on 2021-02-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_profile_from_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_slot_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slot_4', to='profile_app.time_slots'),
        ),
    ]
