# Generated by Django 3.1 on 2021-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_profile_preferred_slot_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_slot_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_slot_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_slot_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_slot_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_slot_1',
            field=models.ManyToManyField(blank=True, to='profile_app.time_slots'),
        ),
    ]
