# Generated by Django 3.1 on 2021-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_auto_20210221_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='from_session',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=10, null=True),
        ),
    ]
