# Generated by Django 3.1 on 2021-02-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_auto_20210221_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_slot_1',
            new_name='preferred_slots',
        ),
    ]
