# Generated by Django 3.1 on 2021-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_auto_20210221_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='from_semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10, null=True),
        ),
    ]
